[package]
name = "sns-discord"
version = "0.1.0"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netlify_lambda = { git = "https://github.com/simnalamburt/aws-lambda-rust-runtime", branch = "tokio-1.0" }
tokio = "1.0.1"
hyper = { version = "0.14.1", features = ["client", "http2", "http1"] }
hyper-rustls = "0.22.0"
serde_json = "1.0.60"
once_cell = "1.5.2"
